export const popularBrands = [
  { name: 'Volkswagen', icon: '/images/VW.png' },
  { name: 'BMW', icon: '/images/BMW.png' },
  { name: 'Mercedes-Benz', icon: '/images/Mercedes.png' },
  { name: 'Audi', icon: '/images/Audi.png' },
  { name: 'Opel', icon: '/images/Opel.png' },
  { name: 'Ford', icon: '/images/Ford.png' },
];

export const carMakes = [
  { name: 'Abarth', value: 'abarth' },
  { name: 'Acura', value: 'acura' },
  { name: 'Alfa Romeo', value: 'alfa-romeo' },
  { name: 'Aston Martin', value: 'aston-martin' },
  { name: 'Audi', value: 'audi' },
  { name: 'Bentley', value: 'bentley' },
  { name: 'BMW', value: 'bmw' },
  { name: 'Bugatti', value: 'bugatti' },
  { name: 'Buick', value: 'buick' },
  { name: 'Cadillac', value: 'cadillac' },
  { name: 'Chevrolet', value: 'chevrolet' },
  { name: 'Chrysler', value: 'chrysler' },
  { name: 'Citroën', value: 'citroen' },
  { name: 'Dacia', value: 'dacia' },
  { name: 'Daewoo', value: 'daewoo' },
  { name: 'Daihatsu', value: 'daihatsu' },
  { name: 'Dodge', value: 'dodge' },
  { name: 'Ferrari', value: 'ferrari' },
  { name: 'Fiat', value: 'fiat' },
  { name: 'Ford', value: 'ford' },
  { name: 'Genesis', value: 'genesis' },
  { name: 'GMC', value: 'gmc' },
  { name: 'Honda', value: 'honda' },
  { name: 'Hummer', value: 'hummer' },
  { name: 'Hyundai', value: 'hyundai' },
  { name: 'Infiniti', value: 'infiniti' },
  { name: 'Isuzu', value: 'isuzu' },
  { name: 'Jaguar', value: 'jaguar' },
  { name: 'Jeep', value: 'jeep' },
  { name: 'Kia', value: 'kia' },
  { name: 'Koenigsegg', value: 'koenigsegg' },
  { name: 'Lamborghini', value: 'lamborghini' },
  { name: 'Lancia', value: 'lancia' },
  { name: 'Land Rover', value: 'land-rover' },
  { name: 'Lexus', value: 'lexus' },
  { name: 'Lincoln', value: 'lincoln' },
  { name: 'Lotus', value: 'lotus' },
  { name: 'Maserati', value: 'maserati' },
  { name: 'Maybach', value: 'maybach' },
  { name: 'Mazda', value: 'mazda' },
  { name: 'McLaren', value: 'mclaren' },
  { name: 'Mercedes-Benz', value: 'mercedes-benz' },
  { name: 'Mercury', value: 'mercury' },
  { name: 'Mini', value: 'mini' },
  { name: 'Mitsubishi', value: 'mitsubishi' },
  { name: 'Nissan', value: 'nissan' },
  { name: 'Opel', value: 'opel' },
  { name: 'Pagani', value: 'pagani' },
  { name: 'Peugeot', value: 'peugeot' },
  { name: 'Pontiac', value: 'pontiac' },
  { name: 'Porsche', value: 'porsche' },
  { name: 'RAM', value: 'ram' },
  { name: 'Renault', value: 'renault' },
  { name: 'Rolls-Royce', value: 'rolls-royce' },
  { name: 'Saab', value: 'saab' },
  { name: 'Saturn', value: 'saturn' },
  { name: 'Seat', value: 'seat' },
  { name: 'Škoda', value: 'skoda' },
  { name: 'Smart', value: 'smart' },
  { name: 'Subaru', value: 'subaru' },
  { name: 'Suzuki', value: 'suzuki' },
  { name: 'Tesla', value: 'tesla' },
  { name: 'Toyota', value: 'toyota' },
  { name: 'Volkswagen', value: 'volkswagen' },
  { name: 'Volvo', value: 'volvo' },
];

export const carModels = {
  "abarth": ["500", "595", "124 Spider"],
  "acura": ["ILX", "MDX", "RDX", "TLX", "NSX"],
  "alfa-romeo": ["Giulia", "Stelvio", "4C", "Spider"],
  "aston-martin": ["DB11", "Vantage", "DBS", "Rapide", "DBX"],
  "audi": [
    "A1", "A3", "A4", "A5", "A6", "A7", "A8", 
    "Q2", "Q3", "Q5", "Q7", "Q8",
    "TT", "TTS", "TT RS",
    "RS3", "RS4", "RS5", "RS6", "RS7",
    "R8", "SQ5", "SQ7", "SQ8", "E-Tron", "E-Tron GT", "Q4 E-Tron"
  ],
  "bentley": ["Bentayga", "Continental", "Flying Spur", "Mulsanne"],
  "bmw": [
    "1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6", "X7", 
    "i3", "i4", "i8", "iX", "Z4", "M2", "M3", "M4", "M5", "M8"
  ],
  "bugatti": ["Veyron", "Chiron", "Divo", "La Voiture Noire"],
  "buick": ["Enclave", "Encore", "Regal", "LaCrosse"],
  "cadillac": ["CT4", "CT5", "XT4", "XT5", "Escalade"],
  "chevrolet": ["Malibu", "Camaro", "Equinox", "Silverado", "Tahoe"],
  "chrysler": ["300", "Pacifica", "Voyager"],
  "citroen": ["C1", "C3", "C4", "C5", "Berlingo"],
  "dacia": ["Duster", "Sandero", "Logan", "Lodgy"],
  "daewoo": ["Matiz", "Nubira", "Lanos", "Leganza"],
  "daihatsu": ["Charade", "Terios", "Cuore", "Sirion"],
  "dodge": ["Charger", "Challenger", "Durango", "Ram", "Journey"],
  "ferrari": ["488", "812", "Portofino", "Roma", "F8 Tributo"],
  "fiat": ["500", "Panda", "Tipo", "Punto", "Doblo"],
  "ford": [
    "Fiesta", "Focus", "Mustang", "Escape", "Explorer", "Bronco", "F-150", "F-250", "Puma", "Ranger", 
    "Kuga", "Edge", "Mach-E", "Transit", "Expedition"
  ],
  "genesis": ["G70", "G80", "GV80"],
  "gmc": ["Acadia", "Terrain", "Sierra", "Yukon"],
  "honda": ["Civic", "Accord", "CR-V", "Pilot", "Fit"],
  "hummer": ["Civic", "Accord", "CR-V", "Pilot", "Fit", "Ridgeline", "HR-V", "Odyssey", "Passport"],
  "hyundai": ["Elantra", "Santa Fe", "Sonata", "Tucson", "Kona", "Palisade", "Veloster", "Ioniq 5", "Ioniq 6"],
  "infiniti": ["Q50", "Q60", "QX50", "QX80"],
  "isuzu": ["D-Max", "MU-X", "Rodeo"],
  "jaguar": ["XE", "XF", "F-Type", "F-Pace", "I-Pace"],
  "jeep": ["Cherokee", "Wrangler", "Compass", "Grand Cherokee", "Renegade", "Gladiator", "Patriot", "Commander"],
  "kia": ["Rio", "Sportage", "Sorento", "Stinger", "Telluride"],
  "koenigsegg": ["Agera", "Jesko", "Regera"],
  "lamborghini": ["Aventador", "Huracan", "Urus", "Gallardo"],
  "lancia": ["Ypsilon", "Delta", "Thema"],
  "land-rover": ["Range Rover", "Defender", "Discovery", "Evoque"],
  "lexus": ["ES", "GX", "RX", "NX", "IS", "LS", "LX", "RC", "LC", "UX"],
  "lincoln": ["Navigator", "Aviator", "Corsair", "Nautilus"],
  "lotus": ["Elise", "Evora", "Exige", "Emira"],
  "maserati": ["Ghibli", "Levante", "Quattroporte", "GranTurismo"],
  "maybach": ["57", "62", "S-Class"],
  "mazda": ["MX-5", "CX-5", "Mazda3", "Mazda6", "CX-30"],
  "mclaren": ["570S", "720S", "P1", "GT", "Artura"],
  "mercedes-benz": [
    "A-Class", "C-Class", "E-Class", "S-Class", "GLE", "GLC", "G-Class", "CLA", "GLA", "EQC", "EQE", "EQS", 
    "AMG GT", "AMG A 45", "AMG C 63", "AMG G 63"
  ],
  "mercury": ["Milan", "Mountaineer", "Grand Marquis"],
  "mini": ["Cooper", "Clubman", "Countryman"],
  "mitsubishi": ["Outlander", "Eclipse Cross", "Mirage", "Lancer"],
  "nissan": ["Altima", "Sentra", "Leaf", "Pathfinder", "X-Trail"],
  "opel": [
    "Astra", "Corsa", "Mokka", "Insignia", "Zafira", "Grandland", "Crossland", "Combo Life", "Vivaro"
  ],
  "pagani": ["Huayra", "Zonda"],
  "peugeot": ["208", "3008", "5008"],
  "pontiac": ["G8", "G6", "Solstice"],
  "porsche": ["911", "Cayenne", "Panamera", "Macan"],
  "ram": ["1500", "2500", "3500"],
  "renault": ["Clio", "Megane", "Kadjar", "Captur"],
  "rolls-royce": ["Ghost", "Phantom", "Wraith", "Cullinan"],
  "saab": ["9-3", "9-5"],
  "saturn": ["Astra", "Vue", "Outlook"],
  "seat": ["Ibiza", "Leon", "Arona", "Ateca"],
  "skoda": ["Octavia", "Fabia", "Superb", "Kodiaq"],
  "smart": ["Fortwo", "Forfour"],
  "subaru": ["Impreza", "Forester", "Outback", "XV"],
  "suzuki": ["Swift", "Vitara", "Jimny", "Baleno", "S-Cross", "Ignis", "Celerio", "Alto", "Ertiga"],
  "tesla": ["Model S", "Model X", "Model 3", "Model Y", "Cybertruck", "Roadster", "Semi"],
  "toyota": [
    "Corolla", "Camry", "RAV4", "Highlander", "Land Cruiser", "Prius", "Tacoma", "Tundra", "Yaris", "C-HR", "4Runner", "Avalon"
  ],
  "volkswagen": [
    "Golf", "Polo", "Passat", "Tiguan", "Touareg", "ID.4", "ID.3", "ID.Buzz", "Arteon", "T-Cross", "T-Roc", "Sharan"
  ],
  "volvo": [
    "S60", "XC60", "V60", "XC90", "XC40", "S90", "V90", "C40 Recharge", "V40", "V50", "XC70"
  ],
};

export const getYearOptions = () => {
  const currentYear = new Date().getFullYear();
  return Array.from({ length: currentYear - 1899 }, (_, index) => {
    const year = currentYear - index;
    return { value: String(year), label: String(year) };
  });
};

export const bodyTypes = [
  { "value": "Sedan", "label": "Sedan" },
  { "value": "Hatchback", "label": "Hatchback" },
  { "value": "SUV", "label": "SUV" },
  { "value": "Crossover", "label": "Crossover" },
  { "value": "Coupe", "label": "Coupe" },
  { "value": "Convertible", "label": "Convertible" },
  { "value": "Wagon", "label": "Wagon" },
  { "value": "Pickup Truck", "label": "Pickup Truck" },
  { "value": "Van", "label": "Van" },
  { "value": "Minivan", "label": "Minivan" },
  { "value": "Roadster", "label": "Roadster" },
  { "value": "Coupe SUV", "label": "Coupe SUV" },
  { "value": "Fastback", "label": "Fastback" },
  { "value": "Cabriolet", "label": "Cabriolet" },
  { "value": "Microcar", "label": "Microcar" },
  { "value": "Limousine", "label": "Limousine" },
  { "value": "Muscle Car", "label": "Muscle Car" },
  { "value": "Sports Car", "label": "Sports Car" },
  { "value": "Utility Vehicle", "label": "Utility Vehicle" },
  { "value": "Station Wagon", "label": "Station Wagon" },
  { "value": "Targa", "label": "Targa" },
  { "value": "Shooting Brake", "label": "Shooting Brake" }
];

export const monthOptions = [
  { value: 'January', label: 'January' },
  { value: 'February', label: 'February' },
  { value: 'March', label: 'March' },
  { value: 'April', label: 'April' },
  { value: 'May', label: 'May' },
  { value: 'June', label: 'June' },
  { value: 'July', label: 'July' },
  { value: 'August', label: 'August' },
  { value: 'September', label: 'September' },
  { value: 'October', label: 'October' },
  { value: 'November', label: 'November' },
  { value: 'December', label: 'December' },
];